version: '3'

services:
  claude-task-manager:
    build: .
    ports:
      - "9000:9000"
    volumes:
      # Mount these directories to persist data between container restarts
      - ./tasks:/app/tasks
      - ./workspaces:/app/workspaces
      - ./config.json:/app/config.json
    environment:
      # Set environment variables if needed
      - FLASK_ENV=production
      # Uncomment and set these if you need to configure Claude CLI
      # - CLAUDE_API_KEY=your_api_key
      # - CLAUDE_MODEL=claude-3-opus-20240229
    restart: unless-stopped
